### ISSUE TITLE
                                                                                                    java.lang.IllegalArgumentException: Key "-" was already used. If you are using

### ISSUE THREAD

**Issue by gurureddydev** [UmairKhalid786/ComposeTvKeyboard#63]
java.lang.IllegalArgumentException: Key "-" was already used. If you are using

**Comment by Agusioma** [comment]
@gurureddydev  If you haven't solved the issue yet, the hyphen and underscore were repeating themselves in the `constructNumericKeys()` method under `com.techlads.composetvkeyboard.domain.model` . 

```
    private fun constructNumericKeys() = mutableListOf<Key>().apply {
         ...

        // Row five
        add(ABC)
        add(Clear)
        add(Underscore) <--
        add(Space)
        add(Dash) <--
        add(ActionArrow)
    }
```

I have opened a [PR](https://github.com/UmairKhalid786/ComposeTvKeyboard/pull/64) on the same. 

CC @UmairKhalid786
